[book]
authors = ["Scott Techau"]
language = "en"
multilingual = false
title = "Nix Steam Servers"
src = "docs"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/scottbot95/nix-steam-servers"