name: "Run tests/checks for flake"
on:
  push:
    branches:
      - master
jobs:
  check:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v20
      - name: Run checks
        run: |
          nix flake check
